version : "3"

services:
    record_giantwaffle:
        build: ./TwitchRecorder/
        restart: always
        environment:
            - USERNAME=yonixw
            #Quality filters of youtube-dl 
            # Examples: 
            #    https://askubuntu.com/q/486297/570936
            #    https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection
            - QUALITY=[tbr<3072]
        volumes:
            - ./output/:/src/app/allrecords
